# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Dijkstra MyApplication

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Dijkstra: 
	@echo "==== Building Dijkstra ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Dijkstra.make

MyApplication: 
	@echo "==== Building MyApplication ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f MyApplication.make

clean:
	@${MAKE} --no-print-directory -C . -f Dijkstra.make clean
	@${MAKE} --no-print-directory -C . -f MyApplication.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Dijkstra"
	@echo "   MyApplication"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
